### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-mwcir#1]
<1 hour

Think through and *estimate* options for keeping users on the homepage vs. linking to a page that holds the sign-up and login.

If the homepage option is significantly more time, a wireframe for the sign-up/login page is good! if homepage might want to consider some mockups beyond a wireframe.

**June 19 edit**

Please note we're going with the separate page option at this time, due to plugin constraints. May revisit integrated version later if there's time. Also the regular WP login option may solve this problem.

- [x] look and feel development
- [x] forgot password link

**Comment by tylermachado** [comment]
Two options. The log-in form works as a shortcode; thus I'm not sure we can add it to the homepage, but if we can it's no more difficult than it being on its own page, so no time difference.

Either way I think it'll be simple, you'll have your login form for returners, and a "not a member? subscribe now" type button for the rest. The call to action for that is the same either way, I think, as one unified button that still clearly delineates the two options.
[signup.pdf](https://github.com/INN/umbrella-mwcir/files/2018323/signup.pdf)

On the signup page, we'll have the expected forms plus the subscription options. Again, this can be pasted in somewhere as a shortcode -- Leaky Paywall does most of the rest (we can make sure the styles line up nicely). For subscription tiers, LP provides these card-type info boxes.
[suboptions.pdf](https://github.com/INN/umbrella-mwcir/files/2018410/suboptions.pdf)

**Comment by tylermachado** [comment]
Now oriented by order of operations -- one file is the desktop look, one is the mobile.

[flow desktop.pdf](https://github.com/INN/umbrella-mwcir/files/2024243/flow.desktop.pdf)
[flow mobile.pdf](https://github.com/INN/umbrella-mwcir/files/2024244/flow.mobile.pdf)
