### ISSUE TITLE
QA: Style updates for metered alert

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-mwcir#18]
**RESULT:** "Current subscriber? Login here"
- [x] **EXPECT:** add a period to the end -> "Current subscriber? Login here."

----------------------------------------------

**RESULT:** (on desktop) 
"Current subscriber? Login here" does not have a rollover state.
- [x] **EXPECT:** Add an underline (like the SUBSCRIBE button.

----------------------------------------------

**RESULT:** (on desktop) 
red SUBSCRIBE button is top aligned with the "3 free articles left" and pretty close to the text
- [x] **EXPECT:** add `margin: .3em` to the button

----------------------------------------------

**RESULT:** Please subscribe to continue reading and 
to support our mission.
(second line starts with "to support")
- [ ] **EXPECT:** have the line break at reading and start second line with "and to support..."

----------------------------------------------

**RESULT:** (on mobile and tablet)
text and button are left aligned
- [ ] **EXPECT:** center the text and button

**NOTE:** we may be able to bump over the button to the right side (like on the desktop version) for tablet, rather than centered. whatever is easiest.

**Comment by tylermachado** [comment]
Problematic fixes: 
can't easily specify an exact line break, and that part will also depend on screen size at smaller sizes. same issue with centering the elements on small screens, because the actual width of the meter alert is wider than the screen due to the animated entry effect.
