### ISSUE TITLE
CTAs

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-mwcir#2]
< 2 hours

EXPECT:

Create styled mockups for the following:

- [x] Alert for metered content
- [x] Pop-ups
- [x] sidebar calls to action
- [x] options for homepage top right buttons for membership/subscriptions, donate and perhaps newsletter as well?

**June 19 edit**

- [x] homepage CTA
- Meter warning
   - [x] ensure plugins are all there
   - [x] pop-up ad
   - [x] bottom of page warning
   - [x] no more articles wall

**Comment by tylermachado** [comment]
![meterwarning_mobi](https://user-images.githubusercontent.com/3586466/40259037-edaab330-5ac1-11e8-8376-de9a031ee5d5.png)
![meterwarning](https://user-images.githubusercontent.com/3586466/40259039-edbaf9fc-5ac1-11e8-8207-f627e12cd38d.png)

**Comment by tylermachado** [comment]
![popups](https://user-images.githubusercontent.com/3586466/40315270-e51d6e6e-5ce8-11e8-99f5-09789274d6c2.png)

**Comment by tylermachado** [comment]
Option 1:

![buttons1](https://user-images.githubusercontent.com/3586466/40315534-a5a64e80-5ce9-11e8-9476-f0597e625daa.png)

Option 2:

![buttons2](https://user-images.githubusercontent.com/3586466/40315538-a5ef11ba-5ce9-11e8-8941-f201d6ebeef3.png)

**Comment by tylermachado** [comment]
![meterwarning_mobi](https://user-images.githubusercontent.com/3586466/40332647-bf1a1764-5d22-11e8-89e0-be07f3ed967e.png)
![meterwarning](https://user-images.githubusercontent.com/3586466/40332648-bf259490-5d22-11e8-91c6-2a9a60ef60d2.png)

**Comment by tylermachado** [comment]
![new popups](https://user-images.githubusercontent.com/3586466/40332407-07b36030-5d22-11e8-8916-751d1940a5ae.png)

**Comment by tylermachado** [comment]
![buttons1](https://user-images.githubusercontent.com/3586466/40333596-4e5e24fc-5d27-11e8-92d1-e976392d7755.png)

![buttons2](https://user-images.githubusercontent.com/3586466/40333597-4e6cffe0-5d27-11e8-9934-fe7c9dcfbfbe.png)

**Comment by tylermachado** [comment]
![image](https://user-images.githubusercontent.com/3586466/40333696-d4cca69e-5d27-11e8-9d33-5410fd7ca7d8.png)
