### ISSUE TITLE
My Account

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-mwcir#3]
< 3 hours

EXPECT:

Create a wireframe for the account management portal. This is what users will see when logged in as members/subscribers. See Leaky Paywall documentation for guidance.

1. Log in (homepage or login page)
2. Get sent to account management portal where they can:

**June 19 edit**

- [x] update user settings (password, email, etc.)
- [x] view and update current subscriptions (change level, cancel, re-instate, etc.)
- [x] view and update payment settings
- [x] view and update profile info
- [x] delete account
- [x] look and feel development

**Comment by tylermachado** [comment]
This, too, should be mostly configured out of the box, via shortcode on a page we create (with styles of course) so the wireframe is fairly lo-fi.

I'm hoping the "My Subscriptions" table that comes by default is structured nicely enough to style it prettier, especially on mobile.
[myaccount.pdf](https://github.com/INN/umbrella-mwcir/files/2018515/myaccount.pdf)
