### ISSUE TITLE
Refine features list/requirements list

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-mwcir#4]
Proposal: https://docs.google.com/document/d/1NWgW7t2Epo03yXFqdUh9FetuzFKbvSC8Zp3g3VbQEUk/edit?usp=drive_web&ouid=110624423231991971896

**Comment by tylermachado** [comment]
Requirements list and estimates: https://docs.google.com/spreadsheets/u/1/d/1muG43LjB-4yZnxOKGNkxh8YhjNg9obmvFQ4Nc7uhwb4/edit?usp=drive_web&ouid=102640363395498312739
