### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-mwcir#5]
add logins for MailChimp, Leaky Paywall, and Stripe to 1password for configuration work

**Comment by tylermachado** [comment]
Leaky Paywall and Stripe are all set. Mailchimp requires two-factor SMS, as it should, but I'm assuming it's connected to Pamela's phone. Should we advise her to just turn it off?

**Comment by tylermachado** [comment]
these are all saved in 1Pass.
